---
- hosts: idrac
  gather_facts: false
  roles:
    - role: dellemc.openmanage.idrac_os_deployment
      vars:
       hostname: "{{ inventory_hostname }}"
       username: "{{ user }}"
       password: "{{ password }}"
       validate_certs: false
       source:
        protocol: http
        hostname: 100.100.28.4
        iso_path: /omam/raj/sourcehttps
        iso_name: VMware-VMvisor-Installer-8.0.0-20513097.x86_64-Dell_Customized-A00.iso
        is_custom_iso: true
       os_deployment_timeout: 15
