---
- hosts: ome
  connection: local
  name: Fetching ome user facts.
  gather_facts: False

  collections:
    - dellemc.openmanage

  tasks:
    - name: Retrieve basic details of all accounts.
      ome_user_info:
        hostname: "{{ inventory_hostname }}"
        username: "{{ user }}"
        password: "{{ password }}"
        validate_certs: False
